# you can build it by running `kustomize build --enable-helm .`
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component


patchesStrategicMerge:
  - alertmanager-priority.yaml
  - kube-state-metrics-priority.yaml
  - prometheus-priority.yaml
