apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader-reloader

spec:
  template:
    spec:
      containers:
        - name: reloader-reloader
          args:
            - --log-format=json
            - --reload-strategy=annotations