apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

commonLabels:
  app.kubernetes.io/name: keycloak

resources:
  # manifests are mostly copied from https://github.com/keycloak/keycloak-quickstarts/tree/latest/kubernetes-examples
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml

