# see https://prometheus-operator.dev/docs/prologue/quick-start/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: monitoring # some resources are in kube-system instead!

resources:
  # v0.10.0 has issue with too long annotation
  - github.com/prometheus-operator/kube-prometheus?ref=eb0fafd789d14d1c60cb95939449ea4cd500f43f
