apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  priorityClassName: system-cluster-critical

  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus-k8s
      spec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: 'block-ssd-2-replicas'
        resources:
          requests:
            storage: 50Gi
