apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# installs to cert-manager namespace, but this is not the only namespace

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml
  - vault-issuer.yaml
  - cert-manager-test.yaml
  - letsencrypt-prod.yaml
