# this is example so you know how to add custom arguments
apiVersion: builtin
kind: PatchJson6902Transformer
metadata:
  name: argocd-repo-server-affinities
target:
  group: apps
  version: v1
  kind: Deployment
  name: argocd-repo-server
jsonOp: |-
  - op: remove
    path: /spec/template/spec/affinity
