apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  - argocd-application-controller.yaml
  - argocd-cmd-params-cm.yaml
  - argocd-repo-server.yaml
  - argocd-server.yaml
