apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  secretName: plantuml-server-tls
  commonName: plantuml.nazarewk.pw
  dnsNames:
    - plantuml.nazarewk.pw