# based on https://github.com/argoproj/argo-cd/blob/v2.3.1/docs/operator-manual/argocd-cmd-params-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
  server.disable.auth: "false"
