# see https://github.com/argoproj/argo-cd/blob/v2.3.1/docs/operator-manual/argocd-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  users.anonymous.enabled: "false"
  kustomize.buildOptions: "--enable-helm"
