# you can build it by running `kustomize build --enable-helm .`
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

components:
  - components/reloader
  - components/single-node
  - components/haproxy-fix
  - components/ingress

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.2/manifests/ha/install.yaml
  - bases/manage-self
  - namespace.yaml

patchesStrategicMerge:
  - argocd-cmd-params-cm.yaml
  - argocd-cm.yaml
