apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-applicationset-controller
  namespace: argocd
  annotations: {}
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/part-of: argocd
spec:
  ingressClassName: istio
  rules:
    - host: argo-cd-application-set.nazarewk.pw
      http:
        paths:
          - backend:
              service:
                name: argocd-applicationset-controller
                port:
                  name: webhook
            path: /
            pathType: Prefix

  tls:
    - secretName: argocd-applicationset-controller-tls
      hosts:
        - argo-cd-application-set.nazarewk.pw

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-applicationset-controller
  namespace: istio-system
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  secretName: argocd-applicationset-controller-tls
  commonName: argo-cd-application-set.nazarewk.pw
  dnsNames:
    - argo-cd-application-set.nazarewk.pw
