# docs are wrong, see https://github.com/kubernetes-sigs/kustomize/blob/b0d7721049d557063e324c7c2c1ef45bb73e4bdc/api/types/helmchartargs.go#L33-L75
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: rook-ceph-operator

name: rook-ceph
repo: https://charts.rook.io/release
version: v1.8.7

releaseName: rook-ceph
namespace: rook-ceph

valuesInline:
  rbacEnable: true
