# docs are wrong, see https://github.com/kubernetes-sigs/kustomize/blob/b0d7721049d557063e324c7c2c1ef45bb73e4bdc/api/types/helmchartargs.go#L33-L75
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: rook-ceph-cluster

name: rook-ceph-cluster
repo: https://charts.rook.io/release
version: v1.8.7

releaseName: rook-ceph-cluster
namespace: rook-ceph

valuesInline:
  toolbox:
    enabled: true

  clusterName: rook-ceph-nazarewk-krul
  cephClusterSpec:
    dataDirHostPath: /var/lib/rook/rook-ceph-nazarewk-krul

    mon:
      count: 3
      allowMultiplePerNode: true  # running single node for now
    #      volumeClaimTemplate:
    #        storageClassName: local-storage
    #        resources:
    #          requests:
    #            storage: 512Gi

    storage:
      useAllNodes: true
      useAllDevices: false
      config:
        encryptedDevice: 'true'
      devices:
        # NVMe - 1TB - XPG GAMMIX S70 BLADE (2TB total)
        - fullpath: /dev/disk/by-partlabel/nvme-rook-ceph-0
        # SSD - 2TB - Patriot P210
        - fullpath: /dev/disk/by-id/ata-Patriot_P210_2048GB_P210EBBB2109130548
        # SSD - 2TB - Crucial MX500
        - fullpath: /dev/disk/by-id/ata-CT2000MX500SSD1_2139E5D7C184
        # 2x HDD - 4 TB - Seagate Ironwolf Pro
        - fullpath: /dev/disk/by-id/ata-ST4000NE001-2MA101_WS238BWF
        - fullpath: /dev/disk/by-id/ata-ST4000NE001-2MA101_WS23D2Z1

    resources:
      mon:
        limits:
          cpu: 4
          memory: 4Gi

  configOverride: |
    [global]
    mon_allow_pool_delete = true
    osd_pool_default_size = 2
    osd_pool_default_min_size = 1

  cephBlockPools:
    - name: nvme-1-replicas
      spec:
        deviceClass: nvme
        failureDomain: osd
        replicated:
          size: 1
          requireSafeReplicaSize: false
      storageClass:
        name: nvme-1-replicas
        enabled: true
        isDefault: false
        allowVolumeExpansion: true
        reclaimPolicy: Delete
        
    - name: ssd-1-replicas
      spec:
        deviceClass: ssd
        failureDomain: osd
        replicated:
          size: 1
          requireSafeReplicaSize: false
      storageClass:
        name: ssd-1-replicas
        enabled: true
        isDefault: false
        allowVolumeExpansion: true
        reclaimPolicy: Delete

    - name: ssd-2-replicas
      spec:
        deviceClass: ssd
        failureDomain: osd
        replicated:
          size: 2
      storageClass:
        name: ssd-2-replicas
        enabled: true
        isDefault: false
        allowVolumeExpansion: true
        reclaimPolicy: Delete

    - name: hdd-1-replicas
      spec:
        deviceClass: hdd
        failureDomain: osd
        replicated:
          size: 1
          requireSafeReplicaSize: false
      storageClass:
        name: hdd-1-replicas
        enabled: true
        isDefault: false
        allowVolumeExpansion: true
        reclaimPolicy: Delete

    - name: hdd-2-replicas
      spec:
        deviceClass: hdd
        failureDomain: osd
        replicated:
          size: 2
      storageClass:
        name: hdd-2-replicas
        enabled: true
        isDefault: false
        allowVolumeExpansion: true
        reclaimPolicy: Delete

    - name: fast-2-replicas
      spec:
        failureDomain: osd
        replicated:
          size: 2
          hybridStorage:
            primaryDeviceClass: nvme
            secondaryDeviceClass: ssd
      storageClass:
        name: fast-2-replicas
        enabled: true
        isDefault: false
        allowVolumeExpansion: true
        reclaimPolicy: Delete

    - name: fast-3-replicas
      spec:
        failureDomain: osd
        replicated:
          size: 3
          hybridStorage:
            primaryDeviceClass: nvme
            secondaryDeviceClass: ssd
      storageClass:
        name: fast-3-replicas
        enabled: true
        isDefault: false
        allowVolumeExpansion: true
        reclaimPolicy: Delete

    - name: medium-2-replicas
      spec:
        failureDomain: osd
        replicated:
          size: 2
          hybridStorage:
            primaryDeviceClass: ssd
            secondaryDeviceClass: hdd
      storageClass:
        name: medium-2-replicas
        enabled: true
        isDefault: false
        allowVolumeExpansion: true
        reclaimPolicy: Delete

    - name: medium-3-replicas
      spec:
        failureDomain: osd
        replicated:
          size: 3
          hybridStorage:
            primaryDeviceClass: ssd
            secondaryDeviceClass: hdd
      storageClass:
        name: medium-3-replicas
        enabled: true
        isDefault: false
        allowVolumeExpansion: true
        reclaimPolicy: Delete

    - name: medium-4-replicas
      spec:
        failureDomain: osd
        replicated:
          size: 4
          hybridStorage:
            primaryDeviceClass: ssd
            secondaryDeviceClass: hdd
      storageClass:
        name: medium-4-replicas
        enabled: true
        isDefault: false
        allowVolumeExpansion: true
        reclaimPolicy: Delete

  cephFileSystems: []
  cephObjectStores: []
