apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

commonLabels:
  app.kubernetes.io/name: rook
  app.kubernetes.io/component: ceph-cluster

generators:
  - chart.yaml