apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

commonLabels:
  app.kubernetes.io/name: rook
  app.kubernetes.io/component: ceph-cluster
resources:
  - pvs.yaml
generators:
  - chart.yaml

patches:
  - path: patch-storageclass-replace.yaml
    target:
      group: storage.k8s.io
      version: v1
      kind: StorageClass
      labelSelector: app.kubernetes.io/component=ceph-cluster