apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd-system
  destination:
    name: in-cluster
    namespace: argocd
  revisionHistoryLimit: 2
  source:
    path: argocd
    repoURL: https://github.com/nazarewk-iac/k8s-configs
    targetRevision: HEAD
  syncPolicy:
    automated: {}
