apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: argocd-system
spec:
  description: Encapsulates root of ArgoCD infrastructure
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: in-cluster
      namespace: argocd
      server: '*'
    - name: in-cluster
      namespace: istio-system
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - https://github.com/nazarewk-iac/k8s-configs
