apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - namespace.yaml

generators:
  - chart.yaml
patches:
  - target:
      version: v1
      kind: Pod
      name: vault-server-test
    patch: |
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: Replace=true